// <auto-generated />
namespace FlightNode.DataCollection.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DecSix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DecSix));
        
        string IMigrationMetadata.Id
        {
            get { return "201512070258005_DecSix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
