// <auto-generated />
namespace FlightNode.DataCollection.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSiteCodeSiteNameToLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSiteCodeSiteNameToLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201602022110503_AddSiteCodeSiteNameToLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
