// <auto-generated />
namespace FlightNode.DataCollection.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkdayNumVolunteersAndTasksCompleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkdayNumVolunteersAndTasksCompleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201605050229326_WorkdayNumVolunteersAndTasksCompleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
